name: jammu-kashmir
favicon: null
layout_spectrum: 0.12060825200751424
typography_spectrum: 0.5813806944061071
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.22663513477891684
  lightness: 0.18229333870112896
  saturation: 0.5976933983620256
  rhythmicContrast: 0.3425674997270107
purpose: []
